import { useState } from "react";
import { Pencil, Trash2, Repeat2, Wallet, Check } from "lucide-react";
import { categories, type Planner } from "./planner-model";
import { type Entry, money, todayInManila } from "./finance-utils";
type Confirm = (target: { title: string; detail: string; confirmLabel: string; tone?: "danger" | "default"; onConfirm: () => unknown | Promise<unknown> }) => void;
type Props = { data: Planner; entries: Entry[]; save: (p: Record<string, unknown>) => Promise<boolean>; confirm: Confirm; busy: boolean };

export function BudgetPlanner({ data, entries, save, confirm, busy }: Props) {
  const [month, setMonth] = useState(todayInManila().slice(0, 7));
  const [category, setCategory] = useState("Food");
  const [amount, setAmount] = useState("");
  const monthly = entries.filter(e => e.kind === "expense" && e.date.startsWith(month));
  const budgets = data.categoryBudgets[month] || {};
  const names = [...new Set([...categories, ...data.customCategories, ...Object.keys(budgets), ...monthly.map(e => e.category)])];
  const spent = monthly.reduce((n, e) => n + e.amountCents, 0);
  const allocated = Object.values(budgets).reduce((n, x) => n + x, 0);
  return <div className="planner-layout"><section><div className="section-toolbar"><label className="compact-field">Month<input type="month" value={month} onChange={e => setMonth(e.target.value)} required /></label><span>{money(spent)} spent / {money(allocated)} allocated</span></div><div className="envelope-list">{names.map(name => {
    const used = monthly.filter(e => e.category === name).reduce((n, e) => n + e.amountCents, 0), limit = budgets[name];
    const over = limit !== undefined && used > limit;
    return <article className="envelope" key={name}><div className="envelope-head"><span className="tool-symbol"><Wallet size={18}/></span><h2>{name}</h2><button className="icon-control" aria-label={`Edit ${name} budget`} title={`Edit ${name} budget`} onClick={() => { setCategory(name); setAmount(limit === undefined ? "" : String(limit / 100)); document.getElementById("envelope-amount")?.focus(); }}><Pencil size={17}/></button></div><strong>{money(used)} <small>/ {limit === undefined ? "Not set" : money(limit)}</small></strong><progress aria-label={`${name} budget used`} max={Math.max(limit || used || 1, 1)} value={used}/><p className={over ? "over-budget" : ""}>{limit === undefined ? "No category limit yet" : over ? `${money(used - limit)} over budget` : `${money(limit - used)} available`}</p></article>;
  })}</div></section><form className="planner-form form-grid" onSubmit={e => { e.preventDefault(); confirm({ title: "Save category budget?", detail: `${category}: PHP ${amount} for ${month}. This is separate from your weekly spending limit.`, confirmLabel: "Save budget", onConfirm: async () => { if (await save({ action: "category_budget", month, category, amount })) setAmount(""); } }); }}><h2>Plan your month</h2><label>Category<select value={category} onChange={e => setCategory(e.target.value)}>{names.map(name => <option key={name}>{name}</option>)}</select></label><label>Monthly limit (PHP)<input id="envelope-amount" required type="number" min="0" max="10000000" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></label><button className="primary-button" disabled={busy}><Check size={17}/> Save limit</button></form></div>;
}

export function RecurringPlanner({ data, save, confirm, busy }: Props) {
  const blank = { id: "", name: "", amount: "", category: "Bills", nextDate: todayInManila(), frequency: "monthly" };
  const [form, setForm] = useState(blank);
  return <div className="planner-layout"><section><h2>Scheduled expenses</h2><p className="section-description">Review each due occurrence before recording it. No payment is made by this app.</p>{!data.recurring.length && <div className="empty-state"><Repeat2/><strong>No recurring expenses</strong><p>Add rent, subscriptions, or a regular purchase.</p></div>}{data.recurring.map(item => <article className="schedule-row" key={item.id}><div><h3>{item.name}</h3><p>{item.frequency} / Next: {item.nextDate}</p><strong>{money(item.amountCents)}</strong></div><div className="row-actions"><button className="outline-button" disabled={busy || item.nextDate > todayInManila()} onClick={() => confirm({ title: "Record this occurrence?", detail: `${item.name}: ${money(item.amountCents)} on ${item.nextDate}. The schedule advances once.`, confirmLabel: "Record expense", onConfirm: () => save({ action: "recurring_post", id: item.id, expectedDate: item.nextDate }) })}>Record due</button><button className="icon-control" title="Edit schedule" aria-label={`Edit ${item.name}`} onClick={() => setForm({ ...item, amount: String(item.amountCents / 100) })}><Pencil size={18}/></button><button className="icon-control" title="Delete schedule" aria-label={`Delete ${item.name}`} onClick={() => confirm({ title: "Delete schedule?", detail: "Already recorded expenses will stay in your history.", confirmLabel: "Delete", tone: "danger", onConfirm: () => save({ action: "recurring_delete", id: item.id }) })}><Trash2 size={18}/></button></div></article>)}</section><form className="planner-form form-grid" onSubmit={e => { e.preventDefault(); confirm({ title: "Save recurring expense?", detail: `${form.name}, starting ${form.nextDate}.`, confirmLabel: "Save schedule", onConfirm: async () => { if (await save({ ...form, id: form.id || undefined, action: "recurring_save" })) setForm(blank); } }); }}><h2>{form.id ? "Edit schedule" : "New schedule"}</h2><label>Name<input required maxLength={100} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>Amount (PHP)<input required type="number" min="0.01" max="10000000" step="0.01" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })}/></label><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{[...categories, ...data.customCategories].map(c => <option key={c}>{c}</option>)}</select></label><label>Next date<input required type="date" value={form.nextDate} onChange={e => setForm({ ...form, nextDate: e.target.value })}/></label><label>Repeat<select value={form.frequency} onChange={e => setForm({ ...form, frequency: e.target.value })}><option value="monthly">Monthly</option><option value="weekly">Weekly</option></select></label><button className="primary-button" disabled={busy}>Save schedule</button>{form.id && <button type="button" className="outline-button" onClick={() => setForm(blank)}>Cancel edit</button>}</form></div>;
}

export function DebtPlanner({ data, save, confirm, busy }: Props) {
  const blank = { id: "", name: "", balance: "", apr: "0", minimum: "0" };
  const [form, setForm] = useState(blank);
  const [strategy, setStrategy] = useState("snowball");
  const sorted = [...data.debts].sort((a, b) => strategy === "snowball" ? a.balanceCents - b.balanceCents : b.apr - a.apr);
  return <div className="planner-layout"><section><div className="section-toolbar"><h2>Your debts</h2><label className="compact-field">Order<select value={strategy} onChange={e => setStrategy(e.target.value)}><option value="snowball">Smallest balance first</option><option value="avalanche">Highest interest first</option></select></label></div><p className="section-description">Planning order only, not financial advice. Update balances manually; payments do not create expenses automatically.</p>{!sorted.length && <div className="empty-state"><Wallet/><strong>No debts recorded</strong><p>Track money you owe separately from money lent.</p></div>}{sorted.map(item => <article className="schedule-row" key={item.id}><div><h3>{item.name}</h3><strong>{money(item.balanceCents)}</strong><p>{item.apr}% APR / Minimum {money(item.minimumCents)}</p></div><div className="row-actions"><button className="icon-control" title="Edit debt" aria-label={`Edit ${item.name}`} onClick={() => setForm({ id: item.id, name: item.name, balance: String(item.balanceCents / 100), apr: String(item.apr), minimum: String(item.minimumCents / 100) })}><Pencil size={18}/></button><button className="icon-control" title="Delete debt" aria-label={`Delete ${item.name}`} onClick={() => confirm({ title: "Delete debt record?", detail: item.name, confirmLabel: "Delete", tone: "danger", onConfirm: () => save({ action: "debt_delete", id: item.id }) })}><Trash2 size={18}/></button></div></article>)}</section><form className="planner-form form-grid" onSubmit={e => { e.preventDefault(); confirm({ title: "Save debt record?", detail: form.name, confirmLabel: "Save debt", onConfirm: async () => { if (await save({ ...form, id: form.id || undefined, action: "debt_save" })) setForm(blank); } }); }}><h2>{form.id ? "Update balance" : "Add a debt"}</h2><label>Name<input required maxLength={100} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>Balance (PHP)<input required type="number" min="0" max="10000000" step="0.01" value={form.balance} onChange={e => setForm({ ...form, balance: e.target.value })}/></label><label>APR (%)<input required type="number" min="0" max="100" step="0.01" value={form.apr} onChange={e => setForm({ ...form, apr: e.target.value })}/></label><label>Minimum payment (PHP)<input required type="number" min="0" max="10000000" step="0.01" value={form.minimum} onChange={e => setForm({ ...form, minimum: e.target.value })}/></label><button className="primary-button" disabled={busy}>Save debt</button>{form.id && <button type="button" className="outline-button" onClick={() => setForm(blank)}>Cancel edit</button>}</form></div>;
}
